# Generated by Django 4.0.5 on 2022-08-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_employee_pass1_employee_pass2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='pass1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pass2',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
